### ISSUE TITLE
Glyphicons not working with resource aggregate

### ISSUE THREAD

**Issue by tadrian** [OpenNTF/XPagesExtensionLibrary#11]
In the latest release of Extlib 9.0.1v00_11 using the Bootstrap themes the Glyphicons do not work when using enabling "Use runtime optimized JS & CSS resources (xsp.resources.aggregate=true)

**Comment by briangleeson** [comment]
A community member identified the solution over on the OpenNTF forum: http://extlib.openntf.org/main.nsf/project.xsp?r=project/XPages%20Extension%20Library/defects/61DB1D9B6EC336E286257DCC0058B3E8

I've tested it out this morning and it works. Pending some further testing, we should be able to submit the fix in the next ExtLib release.

**Comment by briangleeson** [comment]
This issue has been fixed in release 12 of the Extension Library. Thanks for raising the issue.
