### ISSUE TITLE
formTable Multicolumn with Bootstrap are not displayed as bootstrap columns

### ISSUE THREAD

**Issue by tadrian** [OpenNTF/XPagesExtensionLibrary#12]
Using the example from the Extlib sample database for doing a multicolumn table I can see that it is not responsive, i.e there is no bootstrap columns added, the html only renders a table

here is the sample from extlib sample databasae

    <xe:formColumn style='width: 70%'>
    							<xe:formRow id="formRow12"
								label="First Name:">
								<xp:inputText id="inputText5">
								</xp:inputText>
							</xe:formRow>
							<xe:formRow id="formRow13"
								label="Last Name:">
								<xp:inputText id="inputText6">
								</xp:inputText>
							</xe:formRow>
						</xe:formColumn>
						<xe:formColumn style='width: 30%'>
							<xe:formRow id="formRow19" label="Picture:">
								<xp:image
									url="/.ibmxspres/.extlib/icons/noPhoto.png" id="image1">
								</xp:image>
								<xp:br />
								<xp:fileUpload id="fileUpload1"></xp:fileUpload>
							</xe:formRow>
						</xe:formColumn>

the resulting HTML for this code do a table row and two td. 

Please allow multicolumns to work with bootstrap so that they are responsive

**Comment by briangleeson** [comment]
The formTable renderer has been reworked for Bootstrap themes. If you specify the formColumn styleClass to use bootstrap columns, the multi-column formTables should display correctly across the various screen sizes
