### ISSUE TITLE
Problem with Datetime picker in dialog with Bootstrap theme

### ISSUE THREAD

**Issue by tadrian** [OpenNTF/XPagesExtensionLibrary#13]
Using the Bootstrap theme, the Datepicker in an xe:dialog do not work, the picker goes behind the dialog

    <xe:dialog id="dialog1">
    <xp:inputText id="inputText1">
								<xp:dateTimeHelper id="dateTimeHelper1"></xp:dateTimeHelper>
								<xp:this.converter>
									<xp:convertDateTime type="date"></xp:convertDateTime>
								</xp:this.converter>
							</xp:inputText>
    </xe:dialog id="dialog1">

**Comment by briangleeson** [comment]
This issue has been fixed in release 12 of the Extension Library. Thanks for raising the issue.
