### ISSUE TITLE
Domino Sample REST Service Feature (9.0.1.v00_11_20141217-1000) requires feature "com.ibm.domino.das.feature".

### ISSUE THREAD

**Issue by brakonstantin** [OpenNTF/XPagesExtensionLibrary#17]
Hi!
I am trying to use the latest (ExtensionLibraryOpenNTF-901v00_11.20141217-1000.zip) version of the library from http://extlib.openntf.org. (http://extlib.openntf.org/Projects%5Cpmt.nsf/downloadcounter?openagent&project=XPages%20Extension%20Library&release=901v00_11.20141217-1000&unid=849AB5A1CBA825C986257DB30056EA70&attachment=ExtensionLibraryOpenNTF-901v00_11.20141217-1000.zip)

But when I started installing Domino Sample REST Service Feature (9.0.1.v00_11_20141217-1000) in Domino Designer I got the following error:

Requested operation cannot be performed because it would invalidate the current configuration. See details for more information.
  Domino Sample REST Service Feature (9.0.1.v00_11_20141217-1000) requires feature "com.ibm.domino.das.feature".

But com.ibm.domino.das.feature is not included in ExtensionLibraryOpenNTF-901v00_11.20141217-1000.zip at all. Is there a way to get it fixed?

BR Konstantin.

**Comment by padraic-edwards** [comment]
Issue fixed in Extlib release v15
