### ISSUE TITLE
navbarApplicationLinks don't show up in new Simple Layout Config

### ISSUE THREAD

**Issue by howardtlcc** [OpenNTF/XPagesExtensionLibrary#18]
I was trying out the new simple layout option for the application layout control and I can't get the navbarApplicationLinks to show.

Howard

	<xe:applicationLayout id="applicationLayout1"> 
			   <xp:callback 
					   facetName="facetMiddle" 
					   id="facetMiddle"> 
			   </xp:callback> 
			   <xe:this.facets> 
					   <xp:callback 
							   facetName="facetRight" 
							   id="facetRight" 
							   xp:key="RightColumn"> 
					   </xp:callback> 
					   <xp:callback 
							   facetName="facetLeft" 
							   id="facetLeft" 
							   xp:key="LeftColumn"> 
					   </xp:callback> 
			   </xe:this.facets> 
			   <xp:this.facets></xp:this.facets> 
			   <xe:this.configuration> 
					   <xe:simpleResponsiveConfiguration 
							   fixedNavbar="fixed-top" 
							   navbar="true" 
							   invertedNavbar="true"> 
							   <xe:this.navbarAppLinks> 
									   <xe:basicLeafNode 
											   label="Test 2" 
											   href="http://www.tlcc.com" 
											   title="title"> 
									   </xe:basicLeafNode> 
									   <xe:basicLeafNode label="test 1"></xe:basicLeafNode> 
									   <xe:basicLeafNode label="Test 3"></xe:basicLeafNode> 
							   </xe:this.navbarAppLinks> 
							   <xe:this.navbarUtilityLinks> 
									   <xe:basicLeafNode label="Utility 1"></xe:basicLeafNode> 
									   <xe:basicLeafNode label="Utility 2"></xe:basicLeafNode> 
							   </xe:this.navbarUtilityLinks> 
					   </xe:simpleResponsiveConfiguration> 
			   </xe:this.configuration> 
	</xe:applicationLayout>

**Comment by briangleeson** [comment]
Thanks for reporting this issue. As it is quite severe, we will be hoping to include a fix in the next exltib release.

**Comment by briangleeson** [comment]
A fix for this issue was added to release 13 of the 9.0.1 Extension Library
