### ISSUE TITLE
Enhancement request for REST Data services

### ISSUE THREAD

**Issue by howardtlcc** [OpenNTF/XPagesExtensionLibrary#19]
Please add a way to specify a field that the REST data will reside in. This is needed for some tools like Bootstrap DataTables that expect the data to be be under "data" as shown below.

    {"data": [{"state":"IL","lastname":"Gonzales","firstname":"Adam","city":"New York"}, {"state":"IL","lastname":"Fleming","firstname":"Adella","city":"Buford"},{"state":"FL","lastname":"Ainsworth","firstname":"Adrian","city":"Oshkosh"},{"state":"FL","lastname":"Hall","firstname":"Adrienne","city":"Minneapolis"},

thanks,

Howard

**Comment by padraic-edwards** [comment]
Closing this one as there are no plans to fix. Will reopen if we get a contribution.
