### ISSUE TITLE
Bootstrap Responsive: NavBar and Application links

### ISSUE THREAD

**Issue by yetiman79** [OpenNTF/XPagesExtensionLibrary#22]
I am using the Bootstrap Responsive Theme on a mobile phone.
When I click on the collapsed Application menu icon, the navbar is also expanded.
This is not the expected behaviour. See screenshot for more info.
![bootstrap_bug1](https://cloud.githubusercontent.com/assets/12545954/7750261/77da0008-ffd3-11e4-9590-3e88aaa44ddc.JPG)

**Comment by briangleeson** [comment]
This issue has been logged as SPR #BGLN9ZCMXK. We hope to address this issue in an upcoming release of the Extlib

**Comment by briangleeson** [comment]
This fix has been added to the Extension Library in release 14. Thanks for submitting the fix and contributing to the ExtLib.
