### ISSUE TITLE
DojoExtNameTextBoxRenderer does not use MultipleSeparator...

### ISSUE THREAD

**Issue by sbasegmez** [OpenNTF/XPagesExtensionLibrary#23]
DojoExtNameTextBoxRenderer does not use the declared multiple separator.

There is a problem is on the Renderer inheritence model here. [DojoExtNameTextBoxRenderer](https://github.com/OpenNTF/XPagesExtensionLibrary/blob/master/extlib/lwp/product/runtime/eclipse/plugins/com.ibm.xsp.extlib.controls/src/com/ibm/xsp/extlib/renderkit/dojoext/form/DojoExtNameTextBoxRenderer.java) extends [DojoExtListTextBoxRenderer](https://github.com/OpenNTF/XPagesExtensionLibrary/blob/master/extlib/lwp/product/runtime/eclipse/plugins/com.ibm.xsp.extlib.controls/src/com/ibm/xsp/extlib/renderkit/dojoext/form/DojoExtListTextBoxRenderer.java). In [Line 55](https://github.com/OpenNTF/XPagesExtensionLibrary/blob/master/extlib/lwp/product/runtime/eclipse/plugins/com.ibm.xsp.extlib.controls/src/com/ibm/xsp/extlib/renderkit/dojoext/form/DojoExtListTextBoxRenderer.java#L55), there is;

```java
if(dojoComponent instanceof UIDojoExtListTextBox) {
    UIDojoExtListTextBox c = (UIDojoExtListTextBox)dojoComponent;
    String msep = c.getMultipleSeparator();
    if(!StringUtil.equals(msep, ",")) {
        DojoRendererUtil.addDojoHtmlAttributes(attrs,"msep",msep); // $NON-NLS-1$
    }
....
```

However the *DojoExtNameTextBoxRenderer* component actually extends *AbstractDojoExtListTextBox*. So it skips this part and does not add "msep" attribute to the dojo widget. Therefore, we can't use any delimiter other than "," in NameTextBox

Switching the *instanceof* check to the *AbstractDojoExtListTextBox* fixed the problem but didn't test for side effects and have not issued a pull request...

**Comment by maire-kehoe** [comment]
Issue logged as:
SPR#MKEEA2DH2H XPages Extlib, Dojo Name Text Box control, multipleSeparator problem
We will consider it for the next OpenNTF release.

**Comment by maire-kehoe** [comment]
A fix for this issue was included in the extlib openNTF release 901v00_15. 
The relevant line in the change log is:
MKEEA2DH2H xe:djextNameTextBox multipleSeparator=# was not working
Thanks for reporting the issue.
