### ISSUE TITLE
Dynamic Contents and Dynamic Resource Loading...

### ISSUE THREAD

**Issue by sbasegmez** [OpenNTF/XPagesExtensionLibrary#24]
Custom components and custom controls within a dynamic content cannot load their CSS resources at runtime. I have seen that this is a known issue ([Phil's comment](https://github.com/OpenNTF/XPagesExtensionLibrary/blob/master/extlib/lwp/product/runtime/eclipse/plugins/com.ibm.xsp.extlib.controls/src/com/ibm/xsp/extlib/component/dynamiccontent/AbstractDynamicContent.java#L51)).

Any plan to fix that?

**Comment by padraic-edwards** [comment]
I have opened SPR PEDSA5UT97 to track this issue as the fix is required in core

**Comment by sbasegmez** [comment]
Thx Padraic, this issue causes problems in some types of components and important. Let me know if I can do anything on that.
