### ISSUE TITLE
Bootstrap Pager Renderer should support getStyleClass to set pagination pagination-sm

### ISSUE THREAD

**Issue by guedeWebGate** [OpenNTF/XPagesExtensionLibrary#28]
According to the following class: extlib/lwp/product/runtime/eclipse/plugins/com.ibm.xsp.theme.bootstrap/src/com/ibm/xsp/theme/bootstrap/renderkit/html/extlib/PagerRenderer.java the renderer writes the getStyleClass to the div attribute which is the container (line 129). I would recomment to parse the getStyleClass and write alle pagination-* elements to the followd ul tag (line 136)

This allows to control the size of the pager

**Comment by briangleeson** [comment]
Christian, looking at this I think it would make sense to have all styleClass added to the class of the ul tag, not to the wrapping div.

**Comment by briangleeson** [comment]
A fix for this issue has been delivered to the latest Extlib release (9.0.1 R15)
