### ISSUE TITLE
Extlib Tagcloud is missing a database property

### ISSUE THREAD

**Issue by zeromancer1972** [OpenNTF/XPagesExtensionLibrary#29]
With v13 and the Bluemix capabilities you have to define the datasource different from the design database. The tagcloud currently doesn't provide a property to define the source database for the view to be accessed. The tagcloud currently can not be used in a Bluemix environment.

**Comment by henrylis** [comment]
Hi. Yes this is an issue we are aware of, and are hoping to fix in a future OpenNTF Extlib release. For now it is best of avoid the tagcloud control on Bluemix & we will keep you posted.

**Comment by briangleeson** [comment]
`xsp.tag.cloud.database` xsp property added and only supported in the XPages runtime on Bluemix
