### ISSUE TITLE
Cannot change the appPath when adding a service 

### ISSUE THREAD

**Issue by markyroden** [OpenNTF/XPagesExtensionLibrary#33]
When binding a service the appPath is always defaulted to tododata.nsf.

It would make sense to either let the user add the appPath at the time of service request, or being able to edit it after that as part of the interface.

example default
 "apppath": "bluemix/PSC_Playground/Hybrid/tododata.nsf

![brian](https://cloud.githubusercontent.com/assets/1692884/10024169/9ceb9dc6-611b-11e5-9f84-43f18e67e191.png)

**Comment by briangleeson** [comment]
A new method has been added to the `com.ibm.xsp.bluemix.util.context.DataService` class to help with this: `findDatabaseByName(String dbPath)`. This method takes the path to whatever nsf you specify, and builds up the necessary String to use it in the `databaseName` property of an XPages data source. Effectively it returns `getHost() + "!!" + getRootDir() + dbPath;` where the original findDatabaseName method returned `getHost()+"!!"+getAppPath();`
