### ISSUE TITLE
Responsiveness of picker dialogs

### ISSUE THREAD

**Issue by Roland-AL** [OpenNTF/XPagesExtensionLibrary#40]
Using the picker dialogs (name picker and value picker) recently for a bootstrap project I relized that the dialogs are not yet responsive. Width and Height do not adopt to the window size.
The field width is reduced but not the dialog itself. 
Using the dialog on a small sized screen is difficult/impossible because the values in the value list are partially not visible.
The version used was Bootstrap3.2.0 theme from extlib version 901v00_13

**Comment by briangleeson** [comment]
The pickers and dialogs have been re-worked in release 16 of 901 ExtLib to be properly responsive
