### ISSUE TITLE
associate a tooltipDialog with a inputbox 

### ISSUE THREAD

**Issue by Cumhurata** [OpenNTF/XPagesExtensionLibrary#43]
When i try to associate a tooptip dialog with a inputbox(editBox) the tooltipDialog appears far away from related field. 
I i would like to do is onChange event of an inputBox i have to check a parameter value. If result returns true this tooltipDialog should appear close to inputbox. It appear but nor close to the inputbox :(
It works with CSJS (XSP.openTooltipDialog("#{id:tooltipDialog1}",'#{id:button1}'))
but it does not work SSJS
var c = getComponent("tooltipDialog1"); c.setFor("fieldName"); c.show();
You can see how it looks like at the picture attached to this message. 
![ewg5g](https://cloud.githubusercontent.com/assets/16142241/11574440/617d93ac-9a14-11e5-8e6e-bb521ab28c98.png)

**Comment by briangleeson** [comment]
I don't think this is possible when using server-side javascript, to get the position right. The server-side stuff won't be able to determine where on the client side to display the tooltip correctly. You have to use the `XSP.openTooltipDialog` CSJS approach. Setting the `for` property won't achieve anything, as from what I can see, that is only used by within the code for "openTooltipDialog" function.
