### ISSUE TITLE
DataView Renderer - Empty value at an extra column

### ISSUE THREAD

**Issue by sbasegmez** [OpenNTF/XPagesExtensionLibrary#46]
When a value at an extra column in the DataView is empty, it renders as a `<td style="display:none">` output which causes the row collapses over the hidden cell.

The code is here:

https://github.com/OpenNTF/XPagesExtensionLibrary/blob/master/extlib/lwp/product/runtime/eclipse/plugins/com.ibm.xsp.extlib.controls/src/com/ibm/xsp/extlib/renderkit/html_extended/data/DataViewRenderer.java#L1164

Thx

**Comment by briangleeson** [comment]
Fix submitted in ExtLib release 17
