### ISSUE TITLE
Bootstrap3 theme without default css file

### ISSUE THREAD

**Issue by csakis** [OpenNTF/XPagesExtensionLibrary#49]
It would be nice to have a bootstrap3_blank (**bootblank3**) theme that does not contain and bootstrap.css file, so that I can extend this theme with the default.css or any other themed css, so I could have a light and dark theme based on the **bootblank3** theme without duplicating unnecessary style sheets  .

**Comment by briangleeson** [comment]
You're actually not the first to suggest it, but we've never gotten around to doing it. Could be looked at for the next extlib release, and accompanied by a tutorial on how to use it. Thanks for the suggestion

**Comment by briangleeson** [comment]
This feature, a blank Bootstrap theme, has been added to ExtLib release 17
