### ISSUE TITLE
resource aggregation?

### ISSUE THREAD

**Issue by csakis** [OpenNTF/XPagesExtensionLibrary#51]
I usually create my own XPage template using JQuery, bootstrap, font-awesome, Open Sans font ... . If I do that, all my js and css files are downloaded by a single request, respectively. 
![image](https://cloud.githubusercontent.com/assets/2583367/13086663/6d6e0df0-d4a1-11e5-80df-d9b830e54dc6.png)

I decided to give the newest Extension library a try and use the "built-in" JQuery and Bootstrap. I set the application to resource aggregate and yet this is how my Network activity looks like:
![image](https://cloud.githubusercontent.com/assets/2583367/13086718/a94e391c-d4a1-11e5-8770-61ff35cfa0f7.png)

Dojo.js, bootstrap.js and jquery.js have their own request, and whatever I edded extra as a theme or resource, they get bunched up in one request.

Why does it not aggregate dojo and jquery with my custom scrips and css?

**Comment by briangleeson** [comment]
As it stands, the aggregator in XPages for javascript files only aggregates Dojo files into a single request. Thus the bootstrap, jquery and other js files aren't included in that aggregation. The code behind the aggregator is part of the XPages core, not part of the Extension Library. So to improve/fix this, it could only be done as part of work for Domino Next, and not released via ExtLib on OpenNTF.

**Comment by csakis** [comment]
I understand that. You guys are doing all those things, don't you? It's pretty basic stuff going unnoticed in Domino. Who shall I contact about it?

**Comment by briangleeson** [comment]
It would be a job for our team to enhance the aggregator, so you've already contacted us :)

**Comment by paulswithers** [comment]
Please raise on Aha ideas site. It's out of scope for Ext Lib.
