### ISSUE TITLE
Cannot build latest Extlib - unimplemented methods, has a dependency changed?

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/XPagesExtensionLibrary#54]
See screenshot. It's wanting to implement abstract method CommonDataSource.getParentLogger(). I'm using "maven install" in command line in extlib/lwp folder.

Is CommonDataSource in the m2 repository, and has it changed recently? It sounds like Maven is picking up a different version of that class.

![2016-02-29_22-26-08](https://cloud.githubusercontent.com/assets/3721367/13411192/bdab4a70-df33-11e5-9907-72a82b253f62.jpg)

**Comment by briangleeson** [comment]
Are you building against Java 7 possibly?

**Comment by paulswithers** [comment]
Thanks, Brian, that was exactly the reason. I had a more recent version of Java installed for other work. 

The problem with building in Eclipse looks to be the version of m2e plugin doesn't come embedded with Java 6 any more, which is why I was getting a message about UnsupportedClassVersionError. The solution was on StackOverflow, as ever http://stackoverflow.com/questions/31163198/compile-maven-projects-with-jdk-1-6-in-eclipse-mars.
