### ISSUE TITLE
Bootstrap 4 theme requires tether.js

### ISSUE THREAD

**Issue by csakis** [OpenNTF/XPagesExtensionLibrary#60]
If I change my application theme to Bootstrap4, I get this error message in my console.
![image](https://cloud.githubusercontent.com/assets/2583367/13901033/010ccdc4-eddb-11e5-9b2e-d62ad10efffc.png)

I am not using tooltip anywhere in the application.

**Comment by briangleeson** [comment]
Yes I had come across this issue as well. I'm going to close the issue here, and have opened an issue on the XPagesExtLibX project, where the Bootstrap 4 support is being worked on:
https://github.com/OpenNTF/XPagesExtLibX/issues/21
