### ISSUE TITLE
HelpId for FormLayoutRow

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/XPagesExtensionLibrary#63]
I tried the text here https://www.openntf.org/main.nsf/project.xsp?r=project/XPages%20Extension%20Library/discussions/6A282A7062106AB686257E8F004845DA. This works, but the tooltip only displays the first time it you hover on the image. Subsequent times, Firebug shows the styling is applied, but the opacity is 0 (it's 1 the first time you hover on the tooltip). That explains why it's not showing, but I can't track down what's controlling it. (Domino 9.0.1 FP5, Ext Lib 16)

If the tooltip is not in the help facet, it works fine though. So it seems to be related to what helpId applies rather than the xe:tooltip component. I couldn't see anything obvious in com.ibm.xsp.extlib.controls that relates to opacity or the Dojo fadeIn effect (which also uses opacity).

**Comment by briangleeson** [comment]
You won't like my answer but "it works for me" :) Edited the XPagesExt NSF and tooltip worked fine repeatedly. Domino 9.0.1 FP5, ExtLib 16, Bootstrap3 or OneUI302 themes, Chrome or FF.
The opacity/fade-in is handled [in Dojo code](https://github.com/dojo/dijit/blob/1.9/Tooltip.js#L112), in `dijit.Tooltip`:

    // show it
    domStyle.set(this.domNode, "opacity", 0);
    this.fadeIn.play();

We extend `dijit.Tooltip` in `extlib.dijit.Tooltip` and then utilise that in the TooltipRenderer. In the bootstrap theme, it's further extended by `extlib.responsive.dijit.xsp.bootstrap.Tooltip`.

Here's the code I used, including copy-paste from the OpenNTF discussion.

    <xe:formRow id="formRow1" label="First Name:" labelPosition="left">
        <xp:this.facets>
            <xp:span xp:key="help">
                <xp:image url="/.ibmxspres/.oneuiv302/oneuicompat/iconHelp16.png" alt="Help" id="helpImage1"></xp:image>
                <xe:tooltip id="tooltip1" for="helpImage1" label="Enter your first name."></xe:tooltip>
           </xp:span>
        </xp:this.facets>
        <xp:inputText id="inputText1" disableClientSideValidation="true"></xp:inputText>
    </xe:formRow>

It seems for you that maybe `fadeIn.play()` isn't working on the second or more hovers, so it's just setting opacity to 0

**Comment by paulswithers** [comment]
Thanks, Brian. I'll try different databases and different browsers later and see if I can pinpoint what's different

**Comment by paulswithers** [comment]
The cause was CSS, possibly combined with long help text. I had a style specified ".form-table {width:100%}" which was forcing the help image to the far right of the screen. First time it shows, it displays above the help image, with the end of the tooltip to the left of the help image. Subsequent times the tooltip was displayed differently. When I just used Bootstrap_3 without my custom css, it appeared some way to the right (something else is coming into play for CSS as well, because the Form Table I have is in a custom control with fields extending much wider and this impacts the positioning as well, but just a Form Table dropped on the page appears differently). I think it's actually displaying, but off the screen.

**Comment by briangleeson** [comment]
Thanks Paul. There's some changes to the FormTable control Bootstrap rendering in the works for the next release. So keep an eye out for those in R17
