### ISSUE TITLE
Multiple Servlet Applications Extending DasServlet

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/XPagesExtensionLibrary#69]
I'm creating a plugin using the extension point com.ibm.pvc.webcontainer.application. This is contributing a servlet application using JAX-RS, which will provide REST services for a specific application (so it's not intended to provide the same access to all NSFs on the server, and this may be key). The servlet XML in the web.xml is:
`    <servlet>
        <servlet-name>VanillaServletApp</servlet-name>
        <servlet-class>vanillaservlet.BaseServlet</servlet-class>
        <init-param>
            <param-name>javax.ws.rs.Application</param-name>
            <param-value>vanillaservlet.BaseApplication</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>`

The BaseServlet class extends DasServlet. There are a couple of issues I'm encountering, one severe, one just a warning (see server log messages attached).

1) If I have a single servlet application on the server, it works fine. If I add a second, then the first accessed works fine (it doesn't matter which one I choose), but the second throws an Error 500, with a stack trace error "java.lang.IllegalStateException: Writer already obtained". The first servlet hit continues to work though. It seems the DAS class is not fully clearing the response object, because if my servlet extends `com.ibm.domino.services.AbstractRestServlet` (the class DasServlet extends), it's fine (this is at the end of the stack trace, after an HTTP restart). See this technote for Websphere http://www-01.ibm.com/support/docview.wss?uid=swg24017226. I've tried tracing through the code to work out where a fix would need applying. It may need adding to my own servlet class, but when I tried `response.reset()`, that didn't work.
2) With DasServlet I also get a warning message "Cannot set header. Response already committed." I also found a Websphere technote about that, http://www-01.ibm.com/support/docview.wss?uid=swg1PM84636. I don't get the message when extending AbstractRestServlet, so it may be the same cause, that the response has not been fully reset, which means it can't set the header.

As I say, it doesn't matter which servlet I hit first (and both are identical in the output), the first always works, the second always fails.

There are two questions:
1) Am I wrong to be using DasServlet? Perhaps it is intended as more of a persistent option, and therefore _shouldn't_ reset the response. Perhaps it offers nothing relevant for servlets that are intended to provide access for an external application to a specific NSF, and I should extend `com.ibm.domino.services.AbstractRestServlet` instead. (I notice that OpenNTF Domino API changed from extending the DasServlet to creating a DasService, extending `com.ibm.domino.das.service.RestService`, which may be the better practice approach for providing a REST service that can be applied to all NSFs on the server.)
2) If DasServlet offers benefits, where should the response be correctly flushed.

I'm happy to discuss and show you it in action, if it's easier - I am running the plugins directly from Eclipse, with an environment where I can debug down into ExtLib. (And it goes without saying that if my understanding of which should be used when is wrong, I'm happy to blog.)

[Servlets.zip](https://github.com/OpenNTF/XPagesExtensionLibrary/files/234211/Servlets.zip)
[server stack traces.txt](https://github.com/OpenNTF/XPagesExtensionLibrary/files/234212/server.stack.traces.txt)

**Comment by paulswithers** [comment]
I'm pretty convinced I used the wrong class. The `init()` method of `DasServlet` is synchronized, which I suspect is what's causing the problem and why that overrides the AbstractRestServlet. I think DasServlet shouldn't be overridden, but not sure what the best method of handling this is, to warn fools like me! Maybe just a comment in the class itself.

**Comment by ddelay** [comment]
Paul,

No.  I don't think you want to extend the DasServlet class directly.

Have you seen [this wiki article](https://www-10.lotus.com/ldd/ddwiki.nsf/dx/Create_your_own_Domino_REST_service_using_DAS)?  It describes how extend the DAS servlet with your own JAX-RS resource classes.  This approach uses an Eclipse / OSGi extension point instead of Java class inheritance.

-- Dave

**Comment by paulswithers** [comment]
Thanks, that's what I thought. I saw that article, but I don't want to implement a servlet that will hook into all databases. It's just going to provide REST services for a single application. I think I picked the wrong servlet class, not realising the specific use case for it.

**Comment by guedeWebGate** [comment]
Why not make the class final?

Von meinem iPhone gesendet
