### ISSUE TITLE
Allow glyphicons in all treeNodes

### ISSUE THREAD

**Issue by tadrian** [OpenNTF/XPagesExtensionLibrary#9]
treeNodes used in various exlib components do not currently support the option to add glyphicons to them, please add that.

Related
http://stackoverflow.com/questions/25001393/use-glyphicons-in-pagetree-nodes

**Comment by padraic-edwards** [comment]
Closing this as we going to track this through this issue -> https://github.com/OpenNTF/XPagesExtensionLibrary/issues/8
